hwi_oauth:
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    #resource_owners:
        #facebook:
            #type:                facebook
            #client_id:           '%env(FB_ID)%'
            #client_secret:       '%env(FB_SECRET)%'
            #scope:               "email public_profile"
    firewall_names: [secured_area] # le nom de votre pare-feu
    resource_owners:
        google:
            type:                google
            client_id:           your_google_client_id
            client_secret:       your_google_client_secret
            scope:               "email profile" # Les autorisations que vous souhaitez demander à l'utilisateur
