<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRb7QivU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRb7QivU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRb7QivU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRb7QivU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRb7QivU\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rb7QivU',
    'container.build_id' => 'aea24443',
    'container.build_time' => 1708166681,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRb7QivU');
