controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    

app_search:
    path: /search
    controller: App\Controller\EvenementController::search
    methods: [GET]


