app_search:
  path: /search
  controller: 'App\Controller\EvenementController::search'
  methods: [GET]

app_sponsor:
  path: /sponsor
  controller: 'App\Controller\SponsorController::sponsor'
  methods: [GET]

app_add_sponsor:
  path: /add_sponsor
  controller: 'App\Controller\SponsorController::Addsponsor'
  methods: [GET,POST]
app_chat_index:
    path: /chat
    controller: App\Controller\ChatController::index
    methods: ['GET']

app_chat_show:
    path: /chat/{id}
    controller: App\Controller\ChatController::show
    methods: ['GET']

app_chat_edit:
    path: /chat/{id}/edit
    controller: App\Controller\ChatController::edit
    methods: ['GET', 'POST']

app_chat_new:
    path: /new
    controller: App\Controller\ChatController::new
    methods: ['GET', 'POST']
  

app_supp_sponsor:
  path: '/supp_sponsor/{id}'
  controller: App\Controller\SponsorController::supprimersponsor
  methods: ['GET', 'POST'] # Adjust the HTTP methods as needed
app_modifier_sponsor:
  path: '/modifier_sponsor/{id}'
  controller: App\Controller\SponsorController::Modifiersponsor
  methods: ['GET', 'POST'] # Adjust the HTTP methods as needed
