controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
pdf_view:
    path: /pdf/{filename}
    controller: App\Controller\PdfController::viewPdf
